# Generated by Django 3.0.4 on 2020-05-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200508_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemiologicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.PositiveIntegerField(default=0, verbose_name='Casos confirmados')),
                ('suspect', models.PositiveIntegerField(default=0, verbose_name='Casos suspeitos')),
                ('recovered', models.PositiveIntegerField(default=0, verbose_name='Recuperados')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Óbitos confirmados')),
                ('date', models.DateField(null=True, unique_for_date=True, verbose_name='Data')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Grupo')),
            ],
        ),
    ]
