# Generated by Django 3.0.4 on 2020-06-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemiologicalreport',
            name='discarded',
            field=models.PositiveIntegerField(default=0, verbose_name='Descartados'),
        ),
        migrations.AddField(
            model_name='epidemiologicalreport',
            name='monitored',
            field=models.PositiveIntegerField(default=0, verbose_name='Monitorados'),
        ),
    ]
