# Generated by Django 3.0.4 on 2020-07-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200508_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
