"""
Django settings for smc19 project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.contrib import messages
from django.urls import reverse, reverse_lazy

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open("deploy/django-key") as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitoring.apps.MonitoringConfig',
    'accounts.apps.AccountsConfig',
    'evolution.apps.EvolutionConfig',
    'prediction.apps.PredictionConfig',
    'mathmodels.apps.MathmodelsConfig',
    'dashboard.apps.DashboardConfig',
    'crispy_forms',
    'dynamic_formsets',
    'report.apps.ReportConfig',
    'geolocation.apps.GeolocationConfig',
    'map.apps.MapConfig',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'csp.middleware.CSPMiddleware',
    'django_feature_policy.FeaturePolicyMiddleware',
]

ROOT_URLCONF = 'smc19.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smc19.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.Account'

DEFAULT_CHARSET = 'utf-8'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.

LOGIN_REDIRECT_URL = reverse_lazy('monitoring:index')
LOGOUT_REDIRECT_URL = '/accounts/login'

# Css para ser usado no cripsy forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Classe do bootstrap para as mensagens
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-dark',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

DATE_INPUT_FORMATS = ('%d-%m-%Y', '%Y-%m-%d')

# CSP
if not DEBUG:
    SESSION_SAVE_EVERY_REQUEST = True

    SESSION_COOKIE_AGE = 900 # 15 minutos

    SECURE_HSTS_SECONDS = 15768000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_CSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

CSP_DEFAULT_SRC = ("'self'")
CSP_STYLE_SRC = (
    "'self'",
    "stackpath.bootstrapcdn.com",
    "cdn.jsdelivr.net",
    "unpkg.com"
)
CSP_SCRIPT_SRC = ("'self'")
CSP_FONT_SRC = ("'self'")
CSP_IMG_SRC = (
    "'self'",
    "a.tile.openstreetmap.org",
    "b.tile.openstreetmap.org",
    "c.tile.openstreetmap.org",
    "unpkg.com"
)
CSP_INCLUDE_NONCE_IN = ("style-src", "script-src")
CSP_OBJECT_SRC = ("'none'")
CSP_BASE_URI = ("'none'")

FEATURE_POLICY = {
    'accelerometer': 'none',
    'gyroscope': 'none',
    'magnetometer': 'none',
    'camera': 'none',
    'microphone': 'none',
    'payment': 'none',
}

# Configuração necessária para usar o app messages durante os testes
# Retirado de https://stackoverflow.com/a/60218100/13210255
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

# Usar a variável DEBUG no template
# Retirado de https://stackoverflow.com/questions/11020663/how-do-i-get-a-debug-variable-in-my-django-template-context
INTERNAL_IPS = [
    '127.0.0.1',
]

with open("deploy/maps-api") as f:
    GOOGLE_API_KEY = f.read().strip()
