# Generated by Django 3.0.4 on 2020-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20200511_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighbourhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
    ]
