# Generated by Django 3.0.4 on 2020-05-13 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20200512_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temperature',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='blood_pressure',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator()], verbose_name='Pressão arterial'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='pulse',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulso'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='temperature',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Temperatura'),
        ),
    ]
