# Generated by Django 3.0.4 on 2020-05-13 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20200513_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighbourhood',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='blood_pressure',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('\\dx\\d')], verbose_name='Pressão arterial'),
        ),
    ]
