# Generated by Django 3.0.4 on 2020-05-13 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20200513_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='blood_pressure',
            field=models.CharField(blank=True, default='', error_messages={'required': 'Informa a pressão no formato "NUMEROxNUMERO". Ex.: 12x8 ou 120x80'}, max_length=7, validators=[django.core.validators.RegexValidator('\\dx\\d')], verbose_name='Pressão arterial'),
        ),
    ]
