# Generated by Django 3.0.4 on 2020-05-20 20:54

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_auto_20200516_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True, validators=[validators.only_digits, validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12, validators=[validators.only_digits], verbose_name='Número de telefone'),
        ),
    ]
