# Generated by Django 3.0.4 on 2020-05-27 16:03

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20200527_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='validated',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=11, validators=[validators.only_digits, validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
