# Generated by Django 3.0.4 on 2020-06-25 06:17

import bitfield.models
from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_auto_20200624_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='País de origem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cbo',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='CBO'),
        ),
        migrations.AddField(
            model_name='profile',
            name='death_date',
            field=models.DateField(default=None, null=True, verbose_name='Data do óbito'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Passaporte'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_professional',
            field=models.BooleanField(default=False, verbose_name='Profissional de segurança'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comorbidities',
            field=bitfield.models.BitField([('Y', 'Artrite reumatóide'), ('A', 'Asma'), ('C', 'Bronquite crônica'), ('N', 'Câncer'), ('E', 'Demência'), ('D', 'Diabetes'), ('H', 'Doença cardíacas'), ('L', 'Doença crônica no fígado'), ('R', 'Doença renal crônica'), ('W', 'Doenças reumáticas'), ('P', 'Doença pulmonar crônica'), ('I', 'Imunosuprimido'), ('T', 'Hipertensão'), ('V', 'HIV+'), ('B', 'Obesidade'), ('U', 'Portador de Lúpus'), ('F', 'Gestação de risco'), ('G', 'Cromossômica')], blank=True, default=0, verbose_name='Comorbidades'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, validators=[validators.only_digits, validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Profissão'),
        ),
    ]
