# Generated by Django 3.0.4 on 2020-06-30 18:54

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_auto_20200626_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='collection_date',
            field=models.DateField(blank=True, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data da coleta'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='result_date',
            field=models.DateField(blank=True, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data do resultado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True, validators=[validators.prevent_past_date, validators.prevent_future_date], verbose_name='Data de nascimento'),
        ),
    ]
