# Generated by Django 3.0.4 on 2020-07-02 06:16

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_auto_20200630_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmed_date',
            field=models.DateField(default=None, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data de confirmação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='discarded_date',
            field=models.DateField(default=None, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data de descarte'),
        ),
        migrations.AddField(
            model_name='profile',
            name='monitored_date',
            field=models.DateField(default=None, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data de inicio do monitoramento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recovered_date',
            field=models.DateField(default=None, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data de recuperação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspect_date',
            field=models.DateField(default=None, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data que virou suspeito'),
        ),
    ]
