# Generated by Django 3.0.4 on 2020-07-13 19:28

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_auto_20200702_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='attendance_date',
            field=models.DateField(null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data de atendimento'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão'),
        ),
    ]
