# Generated by Django 3.0.4 on 2020-07-16 14:10

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_auto_20200713_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monitored_date',
            field=models.DateField(default=None, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data do fim do monitoramento'),
        ),
    ]
