# Generated by Django 3.0.4 on 2020-07-23 19:52

from django.db import migrations, models
import django.db.models.deletion
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0003_auto_20200511_1310'),
        ('monitoring', '0026_auto_20200720_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField(blank=True, null=True, validators=[validators.only_after_2020, validators.prevent_future_date], verbose_name='Data de entrada')),
                ('departure', models.DateField(blank=True, null=True, validators=[validators.only_after_2020, validators.prevent_future_date], verbose_name='Data de saída')),
                ('bed_type', models.CharField(blank=True, choices=[('2', 'Leito comum'), ('3', 'UTI')], default='', max_length=1, null=True, verbose_name='Tipo de internação')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prediction.HealthCenter', verbose_name='Unidade de saúde')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Profile')),
            ],
        ),
    ]
