# Generated by Django 3.0.4 on 2020-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_hospitalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='medical_referral',
            field=models.CharField(blank=True, choices=[('2', 'Isolamento'), ('3', 'Não está doente')], default='', max_length=1, verbose_name='Encaminhamento'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='medical_referral_status',
            field=models.CharField(blank=True, choices=[('1', 'Casa')], default='', max_length=1, verbose_name='Situação'),
        ),
    ]
