# Generated by Django 3.0.4 on 2020-07-28 17:55

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_auto_20200723_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='onset',
            field=models.DateField(blank=True, null=True, validators=[validators.only_after_2020, validators.prevent_future_date], verbose_name='Data do surgimento'),
        ),
    ]
