# Generated by Django 3.0.4 on 2020-08-05 17:27

from django.db import migrations, models
import django.db.models.deletion
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_auto_20200728_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Telefone')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('contact_date', models.DateField(validators=[validators.only_after_2020, validators.prevent_future_date], verbose_name='Data do Contato')),
                ('created', models.DateTimeField(editable=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Profile')),
            ],
        ),
    ]
