# Generated by Django 3.0.4 on 2020-08-05 22:13

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, validators=[validators.only_digits, validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='contact',
            name='recurring_contact',
            field=models.BooleanField(default=False, verbose_name='Tem contato frequentemente'),
        ),
    ]
