# Generated by Django 3.0.4 on 2020-08-15 17:09

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_auto_20200805_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estimated_first_symptom',
            field=models.DateField(blank=True, null=True, validators=[validators.prevent_future_date, validators.only_after_2020], verbose_name='Data estimada do primeiro sintoma'),
        ),
    ]
