# Generated by Django 3.0.4 on 2020-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0032_profile_estimated_first_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='result',
            field=models.CharField(choices=[('SR', 'Inconclusivo'), ('PO', 'Positivo'), ('NE', 'Negativo')], default='SR', max_length=2, verbose_name='Resultado do exame'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=models.CharField(choices=[('AN', 'Anosmia (Perda do olfato)'), ('CA', 'Cansaço'), ('CM', 'Confusão mental'), ('CN', 'Congestão nasal'), ('CJ', 'Conjuntivite'), ('DI', 'Diarreia'), ('SB', 'Dificuldade respiratória'), ('ST', 'Dor de garganta'), ('DC', 'Dor de cabeça'), ('AP', 'Dores no corpo'), ('FA', 'Falta de apetite'), ('FV', 'Febre'), ('RN', 'Coriza'), ('NA', 'Náusea'), ('TP', 'Tosse produtiva'), ('TS', 'Tosse seca'), ('VO', 'Vômitos')], default='', max_length=2, verbose_name='Tipo de sintoma'),
        ),
    ]
