# Generated by Django 3.0.4 on 2020-08-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_auto_20200827_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='result',
            field=models.CharField(choices=[('SR', 'Sem resultado'), ('PO', 'Positivo'), ('NE', 'Negativo'), ('IN', 'Inconclusivo')], default='SR', max_length=2, verbose_name='Resultado do exame'),
        ),
    ]
