# Generated by Django 3.0.4 on 2021-03-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_auto_20200827_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='tests',
            field=models.CharField(blank=True, choices=[('RT', 'RT PCR Covid-19'), ('TR', 'Teste Rápido'), ('AD', 'Agendado para o dia'), ('N', 'Não'), ('A', 'Antígeno')], default='', max_length=2, verbose_name='Exames solicitados para COVID-19'),
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data de vacinação')),
                ('dose', models.CharField(choices=[('0', 'Única'), ('1', 'Primeira'), ('2', 'Segunda')], max_length=1, verbose_name='Dose')),
                ('vaccine', models.CharField(choices=[('cb', 'CoronaVac/Butantan'), ('of', 'Oxford/Fiocruz'), ('co', 'Aliança Covax/OMS'), ('cx', 'Covaxin'), ('pb', 'Pfizer/BioNTech'), ('mo', 'Moderna'), ('jj', 'Johnson/Janssen'), ('sv', 'Sputnik V')], max_length=2, verbose_name='Vacina')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Profile')),
            ],
        ),
    ]
