# Generated by Django 3.0.4 on 2021-03-13 12:08

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0036_auto_20210313_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(validators=[validators.prevent_future_date, validators.only_after_2021], verbose_name='Data de vacinação'),
        ),
    ]
