# Generated by Django 3.1.8 on 2021-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_auto_20210313_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='tests',
            field=models.CharField(blank=True, choices=[('RT', 'RT PCR Covid-19'), ('TR', 'Teste Rápido'), ('AD', 'Agendado para o dia'), ('N', 'Não'), ('A', 'Antígeno'), ('S', 'Sorologia')], default='', max_length=2, verbose_name='Exames solicitados para COVID-19'),
        ),
    ]
