# Generated by Django 3.1.12 on 2021-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0038_auto_20210429_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='tests',
            field=models.CharField(blank=True, choices=[('RT', 'RT PCR Covid-19'), ('TR', 'Teste Rápido'), ('AD', 'Agendado para o dia'), ('N', 'Não'), ('A', 'Antígeno'), ('S', 'Sorologia')], default='N', max_length=2, verbose_name='Exames solicitados para COVID-19'),
        ),
    ]
